Repository junyuan-chen/ReadStatTables.jl, pull requests merged in 2022-11, with the labels that each got.

#8 Add additional date/time formats
  docs/src/man/date-and-time-values.md
  src/datetime.jl
Labels: bug, enhancement

#6 Redesign `ReadStatMeta` and add `ReadStatColMeta` for DataAPI.jl v1.13
  Project.toml
  docs/make.jl
  docs/src/man/getting-started.md
  docs/src/man/metadata.md
  docs/src/man/table-interface.md
  src/ReadStatTables.jl
  src/readstat.jl
  src/table.jl
  test/readstat.jl
  test/runtests.jl
  test/table.jl
Labels: enhancement, breaking

#10 Redesign `ReadStatTable` and parser callbacks for performance
  Project.toml
  data/README.md
  data/alltypes.do
  data/alltypes.dta
  docs/src/index.md
  docs/src/man/getting-started.md
  docs/src/man/metadata.md
  docs/src/man/table-interface.md
  src/LabeledArrays.jl
  src/ReadStatTables.jl
  src/columns.jl
  src/datetime.jl
  src/parser.jl
  src/readstat.jl
  src/table.jl
  src/wrappers.jl
  test/LabeledArrays.jl
  test/columns.jl
  test/readstat.jl
  test/runtests.jl
  test/table.jl
Labels: enhancement, breaking, performance

#11 Improve `LabeledArray` and documentation
  docs/src/man/date-and-time-values.md
  docs/src/man/getting-started.md
  docs/src/man/metadata.md
  docs/src/man/table-interface.md
  docs/src/man/value-labels.md
  src/LabeledArrays.jl
  src/ReadStatTables.jl
  src/datetime.jl
  src/parser.jl
  src/table.jl
  test/LabeledArrays.jl
  test/readstat.jl
  test/table.jl
Labels: documentation, enhancement, breaking
